### ISSUE TITLE
Handle the case where the ServiceCatalog entries already exist when creating with CloudFormation template

### ISSUE THREAD

**Issue by cfregly** [data-science-on-aws/oreilly_book#205]
![image](https://user-images.githubusercontent.com/1438064/113790100-717b6c00-96f5-11eb-9352-7cd79fd37b08.png)

**Comment by leschan** [comment]
CloudFormation deployment fails if the AWS Account already has IAM Roles "AmazonSageMakerServiceCatalogProductsUseRole" and/or "AmazonSageMakerServiceCatalogProductsLaunchRole already exists". 

Errors:
"CREATE_FAILED | AmazonSageMakerServiceCatalogProductsUseRole already exists"
"CREATE_FAILED | AmazonSageMakerServiceCatalogProductsLaunchRole already exists"

Update CloudFormation template to use non-standard role name. One simple option is to append last portion of Stack ID to role name:

Properties:
      RoleName:  !Join ["-", ["AmazonSageMakerServiceCatalogProductsLaunchRole", !Select [6, !Split ['-', !Ref AWS::StackId]]]]

Properties:
      RoleName:  !Join ["-", ["AmazonSageMakerServiceCatalogProductsUseRole", !Select [6, !Split ['-', !Ref AWS::StackId]]]]

**Comment by leschan** [comment]
Applied and tested changes.
