### ISSUE TITLE
Chapter 3 - `setup_instance_check_passed` not predefined

### ISSUE THREAD

**Issue by MarcusFra** [data-science-on-aws/oreilly_book#232]
# Issue (regarding main branch)
In the notebook [01_Prepare_Dataset_Autopilot.ipynb](https://github.com/data-science-on-aws/oreilly_book/blob/main/03_automl/01_Prepare_Dataset_Autopilot.ipynb) in the folder [03_automl](https://github.com/data-science-on-aws/oreilly_book/tree/main/03_automl) there is a check called `setup_instance_check_passed` which was not defined earlier in [01_introduction](https://github.com/data-science-on-aws/oreilly_book/tree/main/01_introduction), thus yielding to an error message after execution. The reason seems to be the missing notebook [02_Check_Notebook_Instance.ipynb](https://github.com/data-science-on-aws/oreilly_book/blob/main/01_introduction/archive/02_Check_Environment.ipynb) which was moved to the archive.

Could you please remove the missing notebook from the archive back to the installation instructions?

**Comment by cfregly** [comment]
fixed!
